language: python

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - python -m black . --check
  - python -m flake8 --max-line-length=92
  - python -m coverage run --source='.' manage.py test

after_script:
  - coveralls